LettuceGreenhouse:
  Np: 24  # Prediction horizon for MPC
  Ns: 1   # Number of scenarios for MPC
  sigmad: 0.0 # Standard deviation of the disturbance
  nlp_opts:
    ipopt:
      # linear_solver: ma57
      warm_start_entire_iterate: 'yes'
      nlp_scaling_method: gradient-based
      # hessian_approximation: limited-memory
      max_iter: 5000
      constr_viol_tol: 0.01
      acceptable_constr_viol_tol: 0.1
      acceptable_tol: 0.01
      print_level: 1
    # jit: True
    # compiler: shell
    # jit_options:
    #   flags: ['-Ofast', '-march=native']
    #   compiler: gcc

