LettuceGreenhouse:
  Np: 24  # Prediction horizon for MPC
  Ns: 1   # Number of scenarios for MPC
  sigmad: 0.0 # Standard deviation of the disturbance
  nlp_opts:
    verbose: 0
    print_time: 0
    ipopt:
      warm_start_entire_iterate: 'yes'
      nlp_scaling_method: gradient-based
      max_iter: 5000
      constr_viol_tol: 0.01
      acceptable_constr_viol_tol: 0.1
      acceptable_tol: 1.e-2
      print_level: 0
