nx: 4
ny: 4
nu: 3
nd: 4
dt: 1800.
n_days: 40
start_day: 29
x0: [0.0035, 1.e-3, 15, 0.008]
u0: [0., 0., 50.]
lb_pen_w: [5.e-5, 0.003, 7.e-4]
ub_pen_w: [5.e-5, 0.005, 7.e-4]
constraints:
  co2_supply_min: 0.     # lower bound on CO2 supply rate                [kg{co2} m^{-2} s^{-1}]    0
  co2_supply_max: 1.2   # upper bound on CO2 supply rate                [mg{co2} m^{-2} s^{-1}]    1.2
  vent_min: 0.           # lower bound on ventilation rate               [mm s^{-1}]                 0
  vent_max: 7.5         # upper bound on ventilation rate               [mm s^{-1}]                7.5
  heat_min: 0           # lower bound on energy input through heating   [W m^{-2}]                 0
  heat_max: 150.        # upper bound on energy input through heating   [W m^{-2}]                 150

  co2_min: 500.         # lower bound on CO2 concentration              [ppm]        0
  co2_max: 1600.        # upper bound on CO2 concentration              [ppm]        2.75e-3
  temp_min: 10.         # lower bound on temperature                    [째C]                    6.5
  temp_max: 20.         # upper bound on temperature                    [째C]                    20
  rh_min: 0.            # lower bound on relative humidity              [#]                     0
  rh_max: 80.          # upper bound on relative humidity               [#]                     70

  W_min: 0.002          # lower bound on dry weight                     [kg{crop} m^{-2}]        
  W_max: 0.6            # upper bound on dry weight                     [kg{crop} m^{-2}]        
  state_co2_min: 0.           # lower bound on CO2 concentration              [kg m^{-3} m^{-2}]        0
  state_co2_max: 0.004        # upper bound on CO2 concentration              [kg m^{-3} m^{-2}]        2.75e-3
  state_temp_min: 5.          # lower bound on temperature                    [째C]                    6.5
  state_temp_max: 40.         # upper bound on temperature                    [째C]                    20
  state_vp_min: 0.            # lower bound on vapor pressure                 [Pa]                     0
  state_vp_max: 0.051         # upper bound on vapor pressure                 [Pa]                     70
